# Generated by Django 2.2 on 2023-02-24 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='municipality',
            field=models.CharField(default='SP', max_length=255, verbose_name='Municipality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farm_base.Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='state_short_form',
            field=models.CharField(default='SP', max_length=2, verbose_name='State short form'),
            preserve_default=False,
        ),
    ]
