# Generated by Django 2.2 on 2023-02-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_base', '0002_auto_20230224_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(default='My farm 1', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
